{"name": "Создание заказа с неверным хэшем ингредиента", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "new_user_data = {'email': 'anthony17@example.com', 'name': 'Michael Grimes', 'password': 'z39HKo_m!%'}\n\n    @pytest.fixture\n    def new_user(new_user_data):\n        response = requests.post(Urls.REGISTER_URL, json=new_user_data)\n        response_data = response.json()\n    \n>       return new_user_data, response_data['accessToken']\nE       KeyError: 'accessToken'\n\nconftest.py:23: KeyError"}, "start": 1721932939228, "stop": 1721932939228, "uuid": "baff3fd8-0f33-4eef-b221-7c3477793fd6", "historyId": "8ef85be5d2d4a11e939b1014f1bb699e", "testCaseId": "8ef85be5d2d4a11e939b1014f1bb699e", "fullName": "create_order_test.TestCreateOrder#test_create_order_with_invalid_ingredient_hash", "labels": [{"name": "suite", "value": "create_order_test"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "MacBook-Pro-Ola.local"}, {"name": "thread", "value": "40148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "create_order_test"}]}